/* Creación de la base de datos para centros y estudiantes */

CREATE TABLE Centro (
    id          INTEGER             PRIMARY KEY,
    nombre      VARCHAR(200)        NOT NULL,
    titularidad CHAR(7)             CHECK (titularidad IN ('pública','privada'))
);

CREATE TABLE Estudiante (
    id             INTEGER       PRIMARY KEY /* GENERATED BY DEFAULT AS IDENTITY */,
    nombre         VARCHAR(250)  NOT NULL,
    nacimiento     DATE          NOT NULL,
    centro         INTEGER,

    constraint fk_est_cen FOREIGN KEY(centro) REFERENCES Centro(id)
        ON DELETE SET NULL
        on UPDATE CASCADE
);