package edu.acceso.testjdbc;

import java.nio.file.Path;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.time.LocalDate;

import edu.acceso.testjdbc.domain.Centro;
import edu.acceso.testjdbc.domain.Estudiante;
import edu.acceso.testjdbc.domain.Titularidad;

public class Main {
    public static void main(String[] args) {
        final String dbProtocol = "jdbc:sqlite:";

        // Las bases de datos de SQLite son archivos.
        //Path dbPath = Path.of(System.getProperty("java.io.tmpdir"), "test.db");
        //String dbUrl = String.format("%s%s", dbProtocol, dbPath);

        // Alternativa particular de SQLite: base de datos en memoria.
        String dbUrl = String.format("%s%s", dbProtocol, ":memory:");

        Centro[] centros = new Centro[] {
            new Centro(11004866, "IES Castillo de Luna", Titularidad.PUBLICA),
            new Centro(11700602, "IES Pintor Juan Lara", Titularidad.PUBLICA),
            new Centro(21002100, "IES Padre José Miravent", Titularidad.PUBLICA)
        };

        try(Connection conn = DriverManager.getConnection(dbUrl)) {
            System.out.println("Hemos logrado conectar a la base de datos");

            try(Statement stmt = conn.createStatement()) {
                stmt.execute("PRAGMA foreign_keys = ON");

                stmt.executeUpdate("""
                    CREATE TABLE Centro (
                        id          INTEGER             PRIMARY KEY,
                        nombre      VARCHAR(200)        NOT NULL,
                        titularidad CHAR(7)             CHECK (titularidad IN ('pública','privada'))
                    );
                """);

                stmt.executeUpdate("""
                    CREATE TABLE Estudiante (
                        id_estudiante  INTEGER       PRIMARY KEY /* GENERATED BY DEFAULT AS IDENTITY */,
                        nombre         VARCHAR(250)  NOT NULL,
                        nacimiento     DATE          NOT NULL,
                        centro         INTEGER,

                        constraint fk_est_cen FOREIGN KEY(centro) REFERENCES Centro(id)
                            ON DELETE SET NULL
                            on UPDATE CASCADE
                    );
                """);

            }

            String sqlString = "INSERT INTO Centro VALUES (?, ?, ?);";
            try(PreparedStatement pstmt = conn.prepareStatement(sqlString)) {
                for(Centro centro: centros) {
                    pstmt.setInt(1, centro.getId());
                    pstmt.setString(2, centro.getNombre());
                    pstmt.setString(3, centro.getTitularidad().toString());
                    pstmt.executeUpdate();
                }
            }

            try(Statement stmt = conn.createStatement()) {
                ResultSet rs = stmt.executeQuery("SELECT * FROM Centro");
                while(rs.next()) {
                    int id = rs.getInt("id");
                    String nombre = rs.getString("nombre");
                    Titularidad titularidad = Titularidad.fromString(rs.getString("titularidad"));
                    Centro centro = new Centro(id, nombre, titularidad);
                    System.out.println(centro);
                }
            }

            System.out.println("--- *** ---");

            sqlString = "SELECT * FROM Centro WHERE id = ?";
            try(PreparedStatement pstmt = conn.prepareStatement(sqlString)) {
                pstmt.setInt(1, 11004866);
                ResultSet rs = pstmt.executeQuery();
                while(rs.next()) {
                    int id = rs.getInt("id");
                    String nombre = rs.getString("nombre");
                    Titularidad titularidad = Titularidad.fromString(rs.getString("titularidad"));
                    Centro centro = new Centro(id, nombre, titularidad);
                    System.out.println(centro);
                }

            }

            Estudiante[] estudiantes = new Estudiante[] {
                new Estudiante(null, "Perico de los Palotes", LocalDate.of(2000, 01, 01), centros[0]),
                new Estudiante(null, "Segismundo Vergara", LocalDate.of(2002, 02, 02), null)
            };

            sqlString = "INSERT INTO Estudiante VALUES (?, ?, ?, ?)";
            try(PreparedStatement pstmt = conn.prepareStatement(sqlString)) {
                for(Estudiante estudiante: estudiantes) {
                    pstmt.setObject(1, estudiante.getId(), Types.INTEGER);
                    pstmt.setString(2, estudiante.getNombre());
                    Date nacimiento = Date.valueOf(estudiante.getNacimiento());
                    pstmt.setDate(3, nacimiento);
                    Integer idCentro = estudiante.getCentro() == null ? null : estudiante.getCentro().getId();
                    pstmt.setObject(4, idCentro, Types.INTEGER);
                    pstmt.executeUpdate();
                    try(ResultSet rs = pstmt.getGeneratedKeys()) {
                        if(rs.next()) estudiante.setId(rs.getInt(1));
                        else assert false: "La base de datos no devolvió identificador para el estudiante";
                        System.out.printf("'%s' obtiene el identificador %d.\n", estudiante.getNombre(), estudiante.getId());
                    }
                }
            }
        }
        catch(SQLException err) {
            err.printStackTrace();
            System.err.println("Error de conexión. " + err.getMessage());
        }
    }
}
