package edu.acceso.testjdbc;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;

import org.slf4j.LoggerFactory;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import edu.acceso.testjdbc.dao.CentroDao;
import edu.acceso.testjdbc.dao.EstudianteDao;
import edu.acceso.testjdbc.domain.Centro;
import edu.acceso.testjdbc.domain.Estudiante;
import edu.acceso.testjdbc.domain.Titularidad;

public class Main {

    public static void main(String[] args) {
        final String dbProtocol = "jdbc:sqlite:";

        Logger hikariLogger = (Logger) LoggerFactory.getLogger("com.zaxxer.hikari");
        hikariLogger.setLevel(Level.WARN);

        // Las bases de datos de SQLite son archivos.
        //Path dbPath = Path.of(System.getProperty("java.io.tmpdir"), "test.db");
        //String dbUrl = String.format("%s%s", dbProtocol, dbPath);

        // Alternativa particular de SQLite: base de datos en memoria.
        String dbUrl = String.format("%s%s", dbProtocol, "file::memory:?cache=shared");

        ConnectionPool cp = ConnectionPool.getInstance(dbUrl);

        Centro[] centros = new Centro[] {
            new Centro(11004866, "IES Castillo de Luna", Titularidad.PUBLICA),
            new Centro(11700602, "IES Pintor Juan Lara", Titularidad.PUBLICA),
            new Centro(21002100, "IES Padre José Miravent", Titularidad.PUBLICA)
        };

        
        try(Connection conn = cp.getConnection()) {
            System.out.println("Hemos logrado conectar a la base de datos");

            try(Statement stmt = conn.createStatement()) {
                stmt.execute("PRAGMA foreign_keys = ON");

                stmt.executeUpdate("""
                    CREATE TABLE Centro (
                        id          INTEGER             PRIMARY KEY,
                        nombre      VARCHAR(200)        NOT NULL,
                        titularidad CHAR(7)             CHECK (titularidad IN ('pública','privada'))
                    );
                """);

                stmt.executeUpdate("""
                    CREATE TABLE Estudiante (
                        id             INTEGER       PRIMARY KEY /* GENERATED BY DEFAULT AS IDENTITY */,
                        nombre         VARCHAR(250)  NOT NULL,
                        nacimiento     DATE          NOT NULL,
                        centro         INTEGER,

                        constraint fk_est_cen FOREIGN KEY(centro) REFERENCES Centro(id)
                            ON DELETE SET NULL
                            on UPDATE CASCADE
                    );
                """);

            }

            CentroDao centroDao = new CentroDao(cp);
            EstudianteDao estudianteDao = new EstudianteDao(cp);

            // Agrego los centros a la base de datos.
            centroDao.insert(centros);

            // Compruebo centros.
            System.out.println("--- Lista de centros ---");
            centroDao.get().forEach(System.out::println);
            System.out.println("--- *** ---");

            System.out.println("--- *** ---");
            System.out.println(centroDao.get(11004866));
            System.out.println("--- *** ---");

            Estudiante[] estudiantes = new Estudiante[] {
                new Estudiante(null, "Perico de los Palotes", LocalDate.of(2000, 01, 01), centros[0]),
                new Estudiante(null, "Segismundo Vergara", LocalDate.of(2002, 02, 02), null)
            };

            estudianteDao.insert(estudiantes);

            System.out.println("--- Lista de estudiantes ---");
            for(Estudiante estudiante: estudianteDao.get()) {
                System.out.printf("Estudiante %d: %s.\n", estudiante.getId(), estudiante);
            }
            System.out.println("--- *** ---");
        }
        catch(SQLException err) {
            err.printStackTrace();
            System.err.println("Error de conexión. " + err.getMessage());
        }

        Chorrada.ejecutar();
    }
}
